# .devcontainer/docker-compose.yml
version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:18-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'bombeiros_pi'
    ports:
      - 3306:3306

volumes:
  mysql-data: